server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #关闭自我保护，测试用，正式环境不推荐关闭
  client:
    registerWithEureka: false #默认为true,指定是否被服务端发现
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
