eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #这个是默认地址，不写也会向这个地址注册
    healthcheck:
      enabled: true #eureka 运行时健康状态检测，不要在bootstrap.yml文件中使用，否则会出现意想不到的错误。
  instance:
    instance-id: ${spring.application.name}:${server.port}  #修改实列ID
#    prefer-ip-address: true #开启优先使用IP注册而不是主机名
server:
  port: 31000
spring:
  application:
    name: EUREKA-CLIENT-TEST
  profiles: dev
info:
  message: EUREKA_CLIENT_TEST_DEV
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #这个是默认地址，不写也会向这个地址注册
    healthcheck:
      enabled: true #eureka 运行时健康状态检测，不要在bootstrap.yml文件中使用，否则会出现意想不到的错误。
  instance:
    instance-id: ${spring.application.name}:${server.port}  #修改实列ID
#    prefer-ip-address: true #开启优先使用IP注册而不是主机名
server:
  port: 31001
spring:
  application:
    name: EUREKA-CLIENT-TEST
  profiles: test
info:
  message: EUREKA_CLIENT_TEST_TEST
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #这个是默认地址，不写也会向这个地址注册
    healthcheck:
      enabled: true #eureka 运行时健康状态检测，不要在bootstrap.yml文件中使用，否则会出现意想不到的错误。
  instance:
    instance-id: ${spring.application.name}:${server.port}  #修改实列ID
#    prefer-ip-address: true #开启优先使用IP注册而不是主机名
server:
  port: 31003
spring:
  application:
    name: EUREKA-CLIENT-TEST
  profiles: pro
info:
  message: EUREKA_CLIENT_TEST_PRO


